name: CI

on:
  push:
    branches-ignore:
    - gh-pages

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.1.x'

    - name: Determine Version
      id: gitversion # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.1.0

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build and Package with MSBuild
      working-directory: src
      run: msbuild -t:"Clean;Build;Pack" -restore -p:Configuration=Release -p:"Version=${{ steps.gitversion.outputs.fullSemVer }}" LpSolveDotNet.sln
