name: CI

on:
  push

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v4.1.0
      with:
        versionSpec: '6.1.x'

    - name: Determine Version
      id: gitversion # step id used as a reference for output values
      uses: gittools/actions/gitversion/execute@v4.1.0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Restore dependencies
      run: dotnet restore ./src/LpSolveDotNet.sln

    - name: Build and Package Nuget
      run: dotnet pack --no-restore --configuration Release -p:"Version=${{ steps.gitversion.outputs.fullSemVer }}" ./src/LpSolveDotNet.sln
